export enum SEASON {
  WINTER = 0,
  SUMMER = 1
}

export enum FOOD {
  PASTA_RISO_ASCIUTTI = 0,
  PASTA_RISO_BRODO,
  FARRO_ORZO,
  TORTELLINI_ASCIUTTI,
  TORTELLINI_BRODO,
  GNOCCHI_PATATE,
  LASAGNE,
  POLLO_CONIGLIO,
  TACCHINO_FARAONA,
  AGNELLO_MAIALE,
  TRIPPA,
  PESCE_GENERALE,
  MITILI_SEPPIA_RAZZA,
  CALAMARO_TROTA,
  BACCALA_STOCCAFIS,
  WURSTEL,
  PATATE,
  FAGIOLI,
  PISELLI_FAGIOLINI,
  CAROTE,
  CECI,
  CAVOLFIORE,
  ZUCCHINE,
  PURE,
  FINOCCHI,
  VERDURE
}